name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  audit:
    name: brew audit + test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Homebrew/actions/setup-homebrew@master

      - name: Tap local repo
        run: brew tap glsuite/tools .

      - name: brew audit
        run: brew audit --strict glsuite/tools/gltrace

      - name: brew install
        run: brew install glsuite/tools/gltrace

      - name: brew test
        run: brew test glsuite/tools/gltrace
